version: "3.8"


volumes:
  opbnb_data:

services:
  etl:
    build:
      context: ./etl
    environment:
      DB_HOST: db
      DB_NAME: opbnbdata
      DB_PASSWORD: wordpass
      # PROVIDER_URI: https://opbnb-mainnet-rpc.bnbchain.org
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      # - ./etl/jobs:/app/jobs
    # for debugging container changes
    # command: tail -f /dev/null

  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: wordpass
      POSTGRES_USER: postgres
      POSTGRES_DB: opbnbdata
    volumes:
      - opbnb_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  viewer:
    build:
      context: ./viewer
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: wordpass
      DB_NAME: opbnbdata
    # volumes:
    #   - ./viewer/src:/app/src
    depends_on:
      - db
    # for debugging container changes
    # command: tail -f /dev/null
